e79b0c217483bfa4:
  hyperparameters:
    n_estimators: 500
    max_depth: 14
    min_samples_split: 12
    min_samples_leaf: 10
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: 2026-01-27T18:17:45,061
  n_trials: 89
9f4022dfd903badf:
  hyperparameters:
    n_estimators: 500
    max_depth: 14
    min_samples_split: 12
    min_samples_leaf: 10
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: 2026-01-27T18:17:45,061
  n_trials: 89
94c0f16ee21506ef:
  hyperparameters:
    n_estimators: 1000
    max_depth: 22
    min_samples_split: 4
    min_samples_leaf: 9
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-01-28T16:24:11.399184'
  n_trials: 150
ba6aa402600b6914:
  hyperparameters:
    n_estimators: 900
    max_depth: 12
    min_samples_split: 7
    min_samples_leaf: 9
    max_features: log2
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-01-29T10:44:42.582519'
  n_trials: 150
e9c941c74c6de3b0:
  hyperparameters:
    n_estimators: 450
    max_depth: 14
    min_samples_split: 6
    min_samples_leaf: 8
    max_features: log2
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-01-30T13:13:05.504723'
  n_trials: 150
9bbfab124dbad173:
  hyperparameters:
    n_estimators: 400
    max_depth: 15
    min_samples_split: 7
    min_samples_leaf: 6
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-02T10:23:12.287290'
  n_trials: 150
c18cbb36edb22fc9:
  hyperparameters:
    n_estimators: 500
    max_depth: 15
    min_samples_split: 8
    min_samples_leaf: 7
    max_features: log2
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-02T11:02:38.184395'
  n_trials: 150
c8828b0ddd6c386c:
  hyperparameters:
    n_estimators: 350
    max_depth: 15
    min_samples_split: 7
    min_samples_leaf: 6
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-02T12:17:13.541428'
  n_trials: 150
be025053aef2a324:
  hyperparameters:
    n_estimators: 500
    max_depth: 24
    min_samples_split: 8
    min_samples_leaf: 4
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-02T14:46:46.363131'
  n_trials: 150
051e42ca4d70fb68:
  hyperparameters:
    n_estimators: 400
    max_depth: 16
    min_samples_split: 6
    min_samples_leaf: 5
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-02T19:15:52.317204'
  n_trials: 150
31eccef1643c6fb0:
  hyperparameters:
    n_estimators: 450
    max_depth: 17
    min_samples_split: 8
    min_samples_leaf: 7
    max_features: sqrt
    random_state: 42
    n_jobs: -1
    verbose: 0
  optimized_at: '2026-02-03T14:57:32.533185'
  n_trials: 150
